from .authapi import authapi
from .main import main
from .post import posts
from .reviews import reviews
from .profile import profile
from .payments import payments
from .reviews import reviews
from .add import add
from .fav import fav
